services:
  maximus:
    build:
      context: .
      args:
        SERVICE: maximus
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/db
    healthcheck:
      test: python -c 'import httpx; httpx.get("http://localhost:8080/health")'
      interval: 1s
      timeout: 1s
      retries: 3
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13.9
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "$$POSTGRES_DB"]
      interval: 1s
      timeout: 60s
      retries: 5
