services:
  maximus:
    build:
      context: .
      args:
        SERVICE: maximus
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/db
    healthcheck:
      test: python -c 'import httpx; httpx.get("http://localhost:8080/health")'
      interval: 1s
      timeout: 1s
      retries: 3
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13.9
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"]
      interval: 1s
      timeout: 60s
      retries: 5

  meetup:
    build:
      context: .
      args:
        SERVICE: gratters/meetup
    environment:
      MAXIMUS_URL: http://maximus:8080/
      MAXIMUS_API_KEY: 00000000-0000-0000-0000-000000000001
    depends_on:
      maximus:
        condition: service_healthy

  eventbrite:
    build:
      context: .
      args:
        SERVICE: gratters/eventbrite
    environment:
      MAXIMUS_URL: http://maximus:8080/
      MAXIMUS_API_KEY: 00000000-0000-0000-0000-000000000001
    depends_on:
      maximus:
        condition: service_healthy

  luma:
    build:
      context: .
      args:
        SERVICE: gratters/luma
    environment:
      MAXIMUS_URL: http://maximus:8080/
      MAXIMUS_API_KEY: 00000000-0000-0000-0000-000000000001
    depends_on:
      maximus:
        condition: service_healthy
