"""add name

Revision ID: f0f00381a72a
Revises: e9f2f1d002fd
Create Date: 2024-07-28 18:15:51.456365

"""
import os
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f0f00381a72a'
migrations = sorted(
    filter(
        lambda f: not f.startswith('_'), os.listdir(os.path.dirname(__file__))
    )
)
down_revision: Union[str, None] = migrations[
    migrations.index(os.path.basename(__file__)) - 1
].split('_')[4]
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('name', sa.String(), nullable=True))
    op.execute('UPDATE events SET name = \'\'')
    op.alter_column('events', 'name', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'name')
    # ### end Alembic commands ###
