[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["gratus"]

[project]
name = "gratus"
version = "0.1"
requires-python = ">=3.11"
dependencies = [
  "pydantic==2.8.2",
]

[project.optional-dependencies]
dev = [
]
