"""events

Revision ID: 0fe8c00d5374
Revises: e9f2f1d002fd
Create Date: 2024-08-02 16:47:35.635483

"""
import os
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0fe8c00d5374'
migrations = sorted(
    filter(
        lambda f: not f.startswith('_'), os.listdir(os.path.dirname(__file__))
    )
)
down_revision: Union[str, None] = migrations[
    migrations.index(os.path.basename(__file__)) - 1
].split('_')[4]
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'events',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('date_start', sa.DateTime(), nullable=False),
        sa.Column('date_end', sa.DateTime(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('location', sa.String(), nullable=False),
        sa.Column('url', sa.String(), nullable=False),
        sa.Column('mandatory_registration', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
