[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools >= 61.0"]

[tool.setuptools]
py-modules = ["models"]

[project]
dependencies = [
  "pydantic==2.8.2",
]
name = "models"
requires-python = ">=3.11"
version = "0.1"

[project.optional-dependencies]
dev = []
