[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools >= 61.0"]

[tool.setuptools]
py-modules = ["luma"]

[project]
dependencies = []
name = "luma"
requires-python = ">=3.11"
version = "0.1"

[project.optional-dependencies]
dev = []
