# generated by datamodel-codegen:
#   filename:  evt-1Ah5VleTtMDiezj.json
#   timestamp: 2024-09-27T21:49:30+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class GeoAddressInfo(BaseModel):
    full_address: str | None = Field(default=None)


class Event(BaseModel):
    name: str
    url: str
    end_at: str
    start_at: str
    geo_address_info: GeoAddressInfo
    geo_longitude: str
    geo_latitude: str


class LumaEvent(BaseModel):
    api_id: str
    event: Event
    description_mirror: dict[str, Any]
